[package]
name = "australis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = {git = "https://github.com/kangalioo/poise"}
tokio = {version = "1.14.0", features = ["rt-multi-thread"]}